name: folio
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  logging: ^1.1.1
  clock: ^1.1.1
  rxdart: ^0.27.7
  dartz: ^0.10.1
  flutter_riverpod: ^2.2.0
  shared_preferences: ^2.0.18
  go_router: ^6.4.0
  url_strategy: ^0.2.0
  logging_appenders: ^1.0.1
  rx_command: ^6.0.1
  yet_another_observer: ^2.0.0
  formz: ^0.4.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.0
  collection: ^1.17.1
  flex_color_scheme: ^7.0.0-dev.2
  material_color_utilities: ^0.2.0
  google_fonts: ^4.0.3
  boxy: ^2.0.8
  dynamic_color: ^1.6.2
  layout: ^1.0.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # metrics to measure code arch decisios
  dart_code_metrics: ^5.6.0
  # dcm extra lints rules as presets
  dart_code_metrics_presets: ^1.4.1
  # opinionated lint rule set
  lint: ^2.1.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  go_router_builder: ^1.1.7
  riverpod_generator: ^2.0.0
  mocktail: ^0.3.0
  mockingjay: ^0.3.0
  golden_toolkit: ^0.15.0
  
    

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/google_fonts/
