name: grott_folio
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fpdart: ^0.5.0
  equatable: ^2.0.5
  flutter_platform_widgets: ^3.2.0
  flutter_riverpod: ^2.3.2
  flutter_adaptive_scaffold: ^0.1.2
  flex_color_scheme: ^7.0.0-dev.3
  google_fonts: ^4.0.3
  collection: ^1.17.1
  url_strategy: ^0.2.0
  catcher: ^0.7.0
  logging: ^1.1.1
  logging_appenders: ^1.0.2
  boxy: ^2.0.9
  shared_preferences: ^2.0.20
  beamer: ^1.5.3
  go_router: ^6.5.0
  url_launcher: ^6.1.10
  intl_utils: ^2.8.2
  font_awesome_flutter: ^10.4.0
  meta_seo: ^3.0.5
  usage: ^4.1.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.0
  dart_code_metrics_presets: ^1.5.0
  lint: ^2.1.1
  golden_toolkit: ^0.15.0
  mocktail: ^0.3.0
  mockingjay: ^0.3.0
  shouldly: ^0.5.0+1
  page_object: ^0.2.0
  

dependency_overrides:
  intl: ">=0.17.0"

  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/google_fonts/

flutter_intl:
  enabled: true   
  class_name: S
  main_locale: en
  arb_dir: lib/localization
  output_dir: lib/generated
  use_deferred_loading: false   